table Attendance
	lineageTag: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a

	column id
		dataType: int64
		isHidden
		lineageTag: 5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b
		sourceColumn: id
		summarizeBy: none

	column student_id
		dataType: int64
		lineageTag: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
		sourceColumn: student_id
		summarizeBy: none

	column subject_id
		dataType: int64
		lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d
		sourceColumn: subject_id
		summarizeBy: none

	column date
		dataType: dateTime
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		sourceColumn: date

	column status
		dataType: string
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		sourceColumn: status

	measure 'Attendance Rate' =
			VAR TotalRecords = COUNTROWS(Attendance)
			VAR PresentRecords = CALCULATE(COUNTROWS(Attendance), Attendance[status] IN {"present", "late"})
			RETURN IF(TotalRecords = 0, BLANK(), DIVIDE(PresentRecords, TotalRecords) * 100)
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a
		formatString: 0.0"%"

	partition Attendance-4d5e6f7a = m
		mode: import
		source =
				let
				    Source = PostgreSQL_MIS,
				    public_attendance = Source{[Schema="public",Item="attendance"]}[Data]
				in
				    public_attendance

