"""
Simple script to add published field to grades table
Run this if the migration script doesn't work
"""

print("=" * 60)
print("MANUAL MIGRATION INSTRUCTIONS")
print("=" * 60)
print()
print("You need to add the 'published' column to your database.")
print("Please run ONE of the following options:")
print()
print("OPTION 1: Using Flask Shell")
print("-" * 60)
print("1. Start Flask shell:")
print("   flask shell")
print()
print("2. Then run:")
print("   from app import db as database")
print("   conn = database.get_db_connection()")
print("   cur = conn.cursor()")
print("   cur.execute('ALTER TABLE grades ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT FALSE')")
print("   cur.execute('ALTER TABLE subjects ADD COLUMN IF NOT EXISTS results_published BOOLEAN DEFAULT FALSE')")
print("   cur.execute('UPDATE grades SET published = TRUE WHERE published IS NULL')")
print("   conn.commit()")
print("   print('Migration successful!')")
print()
print()
print("OPTION 2: Using PostgreSQL directly (pgAdmin/DBeaver/psql)")
print("-" * 60)
print("Run these SQL commands:")
print()
print("   ALTER TABLE grades ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT FALSE;")
print("   ALTER TABLE subjects ADD COLUMN IF NOT EXISTS results_published BOOLEAN DEFAULT FALSE;")
print("   UPDATE grades SET published = TRUE WHERE published IS NULL;")
print()
print()
print("OPTION 3: From psql command line")
print("-" * 60)
print("   psql -U postgres -d mis_system")
print("   Then paste the SQL from OPTION 2")
print()
print("=" * 60)
