from .core import *
from .teachers import *
from .upgrade import *
from .grades import *
from .subjects import *
from .students import *
from .auth import *
from .classes import *
from .attendance import *
from .moodle import *
from .feedback import *
from .profile import *
